### PR TITLE
Setup-project-branch

### PR DESCRIPTION
**Pull request by Marcraphael12**
Checking if the linters work well, the HTML&CSS files are written in the right way.
If there are any changes to this, thanks to leaving your comment!

### CODE REVIEW

**Comment by Davidosky007** [comment]
# Hi @Marcraphael12, 
👍 Good work on your readme file
👍 your linters are nicely setup
👍 Gitflow was properly implemented
Good job so far 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️
* I suggest that your pull request have a more descriptive title telling what changes have been made and a short summary describing introduced changes in more details. this is a recommended best practice as it makes reviewing easier.
* You can make your commit message more meaningful as a proper commit message can save a great deal of time finding the recent changes related to a bug.

## Optional suggestions
N.A

----------------------------------------------------------------------------------------------------------------------------------------------
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Hi @Marcraphael12 :handshake: , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] As mentioned with the previous reviewer, this Pull Request should have a descriptive title, which shows what kind of changes introduced while working on it, try something like: `Setup project`, `Add initial project files`, ... And also it should have a short description which contains briefly what has been introduced on this Pull request

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project, => You are now left with only one chance to get a review on this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Temmarie — APPROVED** [review]
# Status: Approved ✔️ 

## Hi @Marcraphael12  ,
 
#### Congratulations! 🎉  Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

#### Cheers and Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

**Comment by Marcraphael12** [comment]
With Microverse, we are saying Hello to the world

**Pull request merged**
